# Description: A multi-platform toolkit for creating graphical user interfaces
# URL: http://www.gtk.org/

name=gtk2
version=2.24.11
release=1
source=(http://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-$version.tar.xz)
depends=(atk gdk-pixbuf hicolor-icon-theme libtiff pango libSM libXcursor libXrandr libXi)

build () {
   cd gtk+-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-xkb \
               --disable-xinerama \
               --disable-glibtest \
               --disable-cups \
               --with-x

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{locale,gtk-doc} 

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \; \
                          -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}

check() {
   # Required to build demos, TODO: disable demos compilation
   check_tool gdk-pixbuf-csource
}
