# Description: ppp (Paul's PPP Package) is an open source package which implements the Point-to-Point Protocol (PPP) on Linux and Solaris systems.
# URL: http://ppp.samba.org/

name=ppp
version=2.4.5
release=1
source=(ftp://ftp.samba.org/pub/ppp/ppp-$version.tar.gz)
depends=()

build() {
   cd $name-$version

   find -type f -name Makefile.linux | xargs sed -i "s/\(\$(INSTALL)\) -s/\1/g"

   ./configure

   make CC=$HOST-gcc -j$JOBS
   make DESTDIR=$PKG/usr install

}
