# Description: An image loading library for GTK+
# URL: http://www.gtk.org/

name=gdk-pixbuf
version=2.36.0
release=1
source=(http://ftp.gnome.org/pub/GNOME/sources/$name/${version%.*}/$name-$version.tar.xz)
depends=(glib libpng libtiff libjpeg)

build () {
   cd $name-$version

   echo "gio_can_sniff=no" > config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               --disable-static \
               --without-libjasper \
               --without-x11 \
               --cache-file=config.cache

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/gtk-doc

   # Fix libtool files
   fix_la_files $PKG
}
