# Description: An image loading library for GTK+
# URL: http://www.gtk.org/

name=gdk-pixbuf
version=2.26.5
release=1
source=(http://download.gnome.org/sources/$name/2.26/$name-$version.tar.xz)
depends=(glib libX11 libpng libtiff libjpeg)

build () {
   cd $name-$version

   echo "gio_can_sniff=no" > config.cache

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               --without-libjasper \
               --with-x11 \
               --cache-file=config.cache

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/gtk-doc

   # Fix libtool files
   fix_la_files $PKG
}
