# Description: Snowshoe - The first QT5 browser
# URL: http://snowshoe.openbossa.org/

name=snowshoe
version=git-f131998
release=1
source=(http://buildgear.org/mirror/$name-$version.tar.gz
        snowshoe-fullscreen.patch
        snowshoe.service)
depends=(qtwebkit)

build() {
   cd $name-$version

   patch -p1 < $SRC/snowshoe-fullscreen.patch

   # Set up environment for qmake
   PATH=$SYSROOT/opt/qt5-native/bin:$PATH
   export QMAKESPEC=$SYSROOT/opt/qt5-native/mkspecs/linux-arm-gnueabi-g++

   qmake -r
   make -j $JOBS

   make INSTALL_ROOT=$PKG install

   install -Dm644 $SRC/snowshoe.service $PKG/etc/systemd/system/snowshoe.service
}
