# Description: Avahi is a system which facilitates service discovery on a local network via the mDNS/DNS-SD protocol suite. 
# URL: http://www.avahi.org

name=avahi
version=0.6.31
release=1
source=(http://avahi.org/download/$name-$version.tar.gz)
depends=(glib libdaemon)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-distro=none \
	       --disable-qt3 \
               --disable-qt4 \
               --disable-gtk \
               --disable-gtk3 \
               --disable-gdbm \
               --enable-libdaemon \
               --disable-mono
 
   	      
   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/locale   

   # Fix libtool files
   fix_la_files $PKG
}
