# Description: Avahi is a system which facilitates service discovery on a local network via the mDNS/DNS-SD protocol suite. 
# URL: http://www.avahi.org

name=avahi
version=0.6.31
release=1
source=(http://avahi.org/download/$name-$version.tar.gz)
depends=(glib libdaemon dbus)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-distro=none \
	       --disable-qt3 \
               --disable-qt4 \
               --disable-gtk \
               --disable-gtk3 \
               --disable-gdbm \
	       --disable-python \
               --enable-libdaemon \
               --disable-mono \
               --with-avahi-user=root \
               --with-avahi-group=root \
               --with-avahi-priv-access-group=root \
               --with-autoipd-user=root \
               --with-autoipd-group=root \
               --enable-dbus \
               --with-systemdsystemunitdir=/etc/systemd/system \
               --with-dbus-sys=/etc/dbus-1/system.d


   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/locale

   echo "mdns    5353/tcp" >> $PKG/etc/services
   echo "mdns    5353/udp" >> $PKG/etc/services

   # Fix libtool files
   fix_la_files $PKG
}
