# Description: The standard termulator.
# URL: http://dickey.his.com/xterm/xterm.html

name=xterm
version=297
release=1
source=(ftp://invisible-island.net/$name/$name-$version.tgz)
depends=(libXaw ncurses)
# Depends on: xorg-libxaw xorg-font-alias xorg-font-misc-misc

build() {
  cd $name-$version

  ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr \
              --disable-nls \
              --enable-256-color \
              --enable-wide-chars \
              LDFLAGS="-ltinfo"

  make -j $JOBS
  make install DESTDIR=$PKG
}
