# Description: Library to handle keyboard descriptions
# URL: http://xkbcommon.org

name=libxkbcommon
version=0.4.3
release=1
source=(http://xkbcommon.org/download/$name-$version.tar.xz)
depends=xkeyboard-config

build () {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-x11 

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
