# Description: Describe the build here
# URL: http://www.something.com

name=kmscube
version=git-d04bbd4
release=1
source=(http://buildgear.org/mirror/$name-$version.zip)
depends=(mesa)

build() {
   cd $name-master

   ./autogen.sh

   ./configure --prefix=/usr \
               --host=$HOST \
               --build=$BUILD

   make -j$JOBS
   make DESTDIR=$PKG install
}

