# Description: Collection of tools that interact with the MTD subsystem
# URL: http://www.linux-mtd.infradead.org/index.html
# License: GPLv2

name=mtd-utils
version=2.0.0
release=1
source=(ftp://ftp.infradead.org/pub/mtd-utils/mtd-utils-$version.tar.bz2)
depends=(acl zlib lzo util-linux)

build() {
   cd $name-$version

   ./configure --host=$HOST \
               --build=$BUILD \
               --prefix=/usr

   make -j$JOBS
   make DESTDIR=$PKG install
}
