# Description: X keyboard configuration database
# URL: http://www.freedesktop.org/wiki/Software/XKeyboardConfig
# License: MIT

name=xkeyboard-config
version=2.23
release=1
source=(http://xorg.freedesktop.org/archive/individual/data/$name/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./autogen.sh
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-xkb-rules-symlink=xorg \
               --disable-runtime-deps \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install
}

check() {
   # Test for preinstalled tools
   check_tool xkbcomp "Can be found in Ubuntu package x11-xkb-utils"
}
