# Description: Widely used set of C/C++ libraries providing Unicode and Globalization support.
# URL: http://www.icu-project.org/

name=icu
version=4.8.1.1
release=1
source=(http://download.icu-project.org/files/icu4c/$version/icu4c-${version//./_}-src.tgz)

build() {
#  cd $name

  mkdir build_host
  cd build_host
  $SRC/icu/source/runConfigureICU Linux \
        --prefix=/usr \
        --disable-samples  \
        --disable-tests \
        --enable-rpath 

  make -j $JOBS
  cd ..

  mkdir build_cross
  cd build_cross
  $SRC/icu/source/configure \
        --host=$HOST \
        --prefix=/usr \
        --with-cross-build=$SRC/build_host \
        --enable-shared \
        --disable-samples  \
        --disable-tests  \
        --enable-rpath

  make -j $JOBS
  make DESTDIR=$PKG install

#  rm $PKG/usr/share/icu/$version/license.html
}
