# Description: C++ template library for linear algebra
# URL:         http://eigen.tuxfamily.org

name=eigen
version=3.3.0
release=1
source=(http://bitbucket.org/$name/$name/get/$version.tar.bz2)

build () {
   cd $name-$name-26667be4f70b

   mkdir -p $PKG/usr/include
   cp -r Eigen $PKG/usr/include/
}
