# Description: C++ template library for linear algebra
# URL:         http://eigen.tuxfamily.org

name=eigen
version=3.2.8
release=1
source=(http://bitbucket.org/$name/$name/get/$version.tar.bz2)

build () {
   cd $name-$name-07105f7124f9

   mkdir -p $PKG/usr/include
   cp -r Eigen $PKG/usr/include/
}
