# Description: The Mesa 3D Graphics Library
# URL: http://www.mesa3d.org

name=MesaLib
version=8.0.4
release=1
source=(ftp://ftp.freedesktop.org/pub/mesa/$version/$name-$version.tar.bz2
        0001-Don-t-cross-compile-src-glsl-builtin_compiler.patch)
depends=(libX11 xextproto libXext)

build() {
   cd Mesa-$version

   patch -p1 < $SRC/0001-Don-t-cross-compile-src-glsl-builtin_compiler.patch
   NOCONFIGURE=1 ./autogen.sh

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-dri-drivers=swrast

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   check_tool makedepend
   check_tool python2
   check_tool autoreconf
   check_tool automake
   check_tool aclocal
   check_exist /usr/share/pyshared/libxml2.py
}
