# Description: The Mesa 3D Graphics Library
# URL: http://www.mesa3d.org

name=MesaLib
version=9.1
release=1
source=(ftp://ftp.freedesktop.org/pub/mesa/$version/$name-$version.tar.bz2
        fix-builtin-linking.patch)
depends=(libX11 xextproto libXext glproto libdrm dri2proto
         libXdamage libXfixes)

build() {
   cd Mesa-$version

   patch -p1 < $SRC/fix-builtin-linking.patch

   NOCONFIGURE=1 ./autogen.sh

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-dri-drivers=swrast \
               --with-gallium-drivers=swrast

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   check_tool makedepend "Available in Ubuntu package xutils-dev"
   check_tool python2
   check_tool autoreconf
   check_tool automake
   check_tool aclocal
   check_exist /usr/share/pyshared/libxml2.py "Available in Ubuntu package python-libxml2"
}
