# Description: The Mesa 3D Graphics Library
# URL: http://www.mesa3d.org

name=MesaLib
version=8.0.4
release=1
source=(ftp://ftp.freedesktop.org/pub/mesa/$version/$name-$version.tar.bz2
        0001-Don-t-cross-compile-src-glsl-builtin_compiler.patch)
depends=(libX11 xextproto libXext)

build() {
   cd Mesa-$version

   patch -p1 < $SRC/0001-Don-t-cross-compile-src-glsl-builtin_compiler.patch
   NOCONFIGURE=1 ./autogen.sh

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-dri-drivers=swrast

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \; \
                          -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}

check() {
   check_tool makedepend
   check_tool python2
   check_tool autoreconf
   check_tool automake
   check_tool aclocal
}
