# Description: MPEG1/MPEG2 decoder (includes libmpeg2)
# URL:         http://libmpeg2.sourceforge.net/

name=libmpeg2
version=0.5.1
release=1
source=(http://$name.sourceforge.net/files/$name-$version.tar.gz)
depends=(libsdl libXv)

build () {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --mandir=/usr/share/man \
               --with-gnu-ld --enable-shared \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
