# Description: MPEG1/MPEG2 decoder library
# URL:         http://libmpeg2.sourceforge.net/

name=libmpeg2
version=0.5.1
release=1
source=(http://$name.sourceforge.net/files/$name-$version.tar.gz)
depends=(libsdl)

build () {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls

   make -j $JOBS \
   LIBVO_CFLAGS="-I$SYSROOT/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT" \
   LIBVO_LIBS="-lSDL"
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
