# Description: A library for layout and rendering of text
# URL: http://www.gtk.org/

name=pango
version=1.32.1
release=1
source=(http://download.gnome.org/sources/$name/${version%.*}/$name-$version.tar.xz
        pango.service)
depends=(cairo glib libSM libXext libXft libpng harfbuzz)

build () {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/gtk-doc

   #Install dir for pango.modules
   install -d $PKG/usr/etc/pango

   #Install module initialization service
   install -D $SRC/pango.service $PKG/etc/systemd/system/pango.service

   # Fix libtool files
   fix_la_files $PKG
}
