# Description: simple, small, C++ XML parser
# URL:         http://www.grinninglizard.com/tinyxml/

name=tinyxml
version=2.6.2
release=1
source=(
    http://download.sourceforge.net/project/$name/$name/$version/${name}_${version//./_}.zip 
    entity.patch
)

build() {
   cd $name

   patch -p0 -i $SRC/entity.patch

   soname=lib$name.$version.so
   mkdir -p $PKG/usr/include
   install -m 0644 *.h $PKG/usr/include
   $HOST-g++ -fPIC -shared -Wno-unknown-pragmas -Wno-format -O3 -DTIXML_USE_STL \
             -o $soname tinystr.cpp tinyxml.cpp tinyxmlerror.cpp tinyxmlparser.cpp
   install -D -m 0644 $soname $PKG/usr/lib/$soname
   cd $PKG/usr/lib
   ln -s $soname ${soname%%.*}.so
   ln -s $soname ${soname%.*.*.so}.so
   ln -s $soname ${soname%.*.so}.so
}
