# Description: A data compression library suitable for data de-/compression in real-time.
# URL: http://www.oberhumer.com/opensource/lzo/

name=lzo
version=2.08
release=1
source=(http://www.oberhumer.com/opensource/lzo/download/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-shared

   make -j $JOBS
   make DESTDIR=$PKG install

   ln -s liblzo2.so.2.0.0 $PKG/usr/lib/liblzo.so

   rm -r $PKG/usr/share/doc
   rmdir $PKG/usr/share

   # Fix libtool files
   fix_la_files $PKG
}
