# Description: libFTDI is an open source library to talk to FTDI chips
# URL: http://www.intra2net.com/en/developer/libftdi/
# License: LGPLv2.1

name=libftdi1
version=1.3
release=1
source=(http://www.intra2net.com/en/developer/libftdi/download/$name-$version.tar.bz2)
depends=(libusb boost)

build () {
   cd $name-$version
   sed -i '1iset(CMAKE_FIND_ROOT_PATH '$CROSS_SYSROOT'/usr/lib/)' CMakeLists.txt
   sed -i '1iset(LIBUSB_LIBRARIES '$CROSS_SYSROOT'/usr/lib/libusb-1.0.so)' CMakeLists.txt
   sed -i '1iset(LIBUSB_INCLUDE_DIR '$CROSS_SYSROOT'/usr/include/libusb-1.0/)' CMakeLists.txt
   sed -i '1iset(CMAKE_CXX_COMPILER '$NATIVE_SYSROOT'/bin/'$HOST'-g++)' CMakeLists.txt
   sed -i '1iset(CMAKE_C_COMPILER '$NATIVE_SYSROOT'/bin/'$HOST'-gcc)' CMakeLists.txt
   sed -i '1iset(CMAKE_SYSTEM_NAME Linux)' CMakeLists.txt

   mkdir build
   cd build
   cmake ../
   make DESTDIR=$PKG ftdi1 install
   cp -r $PKG/usr/local/* $PKG/usr/
   rm -rf $PKG/usr/local

   # Fix libtool files
   fix_la_files $PKG
}
