# Description: Ogg bitstream and framing library
# URL: http://www.xiph.org/ogg/

name=libogg
version=1.3.0
release=1
source=(http://downloads.xiph.org/releases/ogg/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
