# Description: Generic Cascading Style Sheet parsing and manipulation toolkit.
# URL: https://launchpad.net/libcroco

name=libcroco
version=0.6.6
release=1
source=(http://download.gnome.org/sources/$name/${version%.*}/$name-$version.tar.xz)
depends=(libxml2 pango)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share
   
   # Fix libtool files
   fix_la_files $PKG

   ln -s libcroco-${version%.*}.la $PKG/usr/lib/libcroco.la
}
