# Description: Yet Another JSON Library
# URL: http://lloyd.github.com/yajl/

name=yajl
version=2.0.4fee1ebe
release=1
source=(http://buildgear.org/mirror/$name-$version.tar.gz)

build() {
   cd lloyd-$name-fee1ebe

   cmake -DCMAKE_INSTALL_PREFIX=/usr \
         -DCMAKE_SYSTEM_NAME=Linux \
         -DCMAKE_C_COMPILER=$HOST-gcc \
         -DCMAKE_LINKER=$NATIVE_SYSROOT/bin/$HOST-ld \
         -DCMAKE_AR=$NATIVE_SYSROOT/bin/$HOST-ar \
         -DCMAKE_NM=$NATIVE_SYSROOT/bin/$HOST-nm \
         -DCMAKE_OBJDUMP=$NATIVE_SYSROOT/bin/$HOST-objdump \
         -DCMAKE_RANLIB=$NATIVE_SYSROOT/bin/$HOST-ranlib \
         -DCMAKE_STRIP=$NATIVE_SYSROOT/bin/$HOST-strip

   make -j $JOBS
   make DESTDIR=$PKG

   install -d $PKG/usr
   cp -a $name-2.0.4/* $PKG/usr/
}

check() {
   check_tool cmake
}
