# Description: JSON implementation in C
# URL:         http://oss.metaparadigm.com/json-c/

name=json-c
version=0.9
release=1
source=(http://oss.metaparadigm.com/$name/$name-$version.tar.gz)
depends=()

build() {
    cd $name-$version
    
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes \
    ./configure --build=$BUILD \
        --host=$HOST \
        --prefix=/usr 
    
    make -j$JOBS
    
    make DESTDIR=$PKG install
       
   # Fix libtool files
   fix_la_files $PKG
}
