# Description: Library that provides hardware graphics acceleration
# URL:         http://www.directfb.org/

name=directfb
version=1.7.6
release=1
source=(http://directfb.net/downloads/Core/DirectFB-${version%.*}/DirectFB-$version.tar.gz)
depends=(zlib libpng libjpeg freetype)

build() {
   cd DirectFB-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-zlib \
               --enable-png \
               --with-gfxdrivers=none

   make -j$JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
