# Description: LibMMS aims to be common mms:// and mmsh:// (Microsoft streaming protocols) parsing library.
# URL: http://sourceforge.net/projects/libmms/

name=libmms
version=0.6.2
release=1
source=(http://downloads.sourceforge.net/project/$name/$name/$version/$name-$version.tar.gz)
depends=(glib)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install	

   # Fix libtool files
   fix_la_files $PKG
}
