# Description: Touch screen library
# URL: http://tslib.berlios.de/

name=tslib
version=1.0
release=1
source=(http://download.berlios.de/$name/$name-$version.tar.bz2)

build () {
   cd $name-$version
  
   ./autogen.sh
   sed 's|LIBFLAGS="|LIBFLAGS="-DUSE_INPUT_API |' -i configure

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc

   sed '/^#define malloc rpl_malloc/d' -i config.h

   make
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
