# Description: Touch screen library
# URL: http://tslib.berlios.de/

name=tslib
version=git5ab6af2e50
release=1
source=(http://buildgear.org/mirror/$name-$version.tar.gz)

build () {
   cd $name-$version
  
   ./autogen.sh
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc

   make -j $JOBS
   make DESTDIR=$PKG install

   install -d $PKG/etc/profile.d
   echo "export TSLIB_CONFFILE=/etc/ts.conf" >> $PKG/etc/profile.d/tslib

   # Fix libtool files
   fix_la_files $PKG
}
