# Description: Userspace library for drm
# URL: http://dri.freedesktop.org/libdrm/

name=libdrm
version=2.4.40
release=1
source=(http://dri.freedesktop.org/libdrm/$name-$version.tar.gz)
depends=libpthread-stubs

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
