# Description: SQL database engine
# URL: http://www.sqlite.org/

name=sqlite
version=3.08.00.00
release=1
source=(http://www.sqlite.org/2013/$name-autoconf-${version//./}.tar.gz)
depends=(ncurses readline)

build () {
   cd $name-autoconf-${version//./}

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --mandir=/usr/share

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
