# Description: a free alternative to the OpenGL Utility Toolkit (GLUT) library.
# URL: http://freeglut.sourceforge.net/

name=freeglut
version=2.8.0
release=1
source=(http://download.sourceforge.net/$name/$name-$version.tar.gz)
depends=(MesaLib libXi)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-warnings

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
