# Description: An ISO MPEG-4 compliant video codec
# URL: http://www.xvid.org/

name=libxvid
version=1.3.2
release=1
source=(http://downloads.xvid.org/downloads/xvidcore-$version.tar.bz2)
depends=(yasm)

build() {
   cd xvidcore/build/generic

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   ln -s libxvidcore.so.4.3 $PKG/usr/lib/libxvidcore.so
}
