# Description: library with NFS-safe locking functions
# URL: https://github.com/miquels/liblockfile
# License: LGPLv2+ GPLv2+

name=liblockfile
version=1.09
release=1
source=(ftp://ftp.debian.org/debian/pool/main/libl/liblockfile/liblockfile\_$version.orig.tar.gz)

build() {
	cd $name-$version

	CC=$HOST-gcc \
	AR=$HOST-ar \
	 ./configure --prefix=/usr \
	            --build=$BUILD \
	            --host=$HOST \
	            --disable-static

	make -j$JOBS

	mkdir -p $PKG/usr/{include,bin,lib}
	mkdir -p $PKG/usr/man/man{1,3}
	make ROOT=$PKG install
}
