# Description: library with NFS-safe locking functions
# URL: https://github.com/miquels/liblockfile
# License: LGPLv2+ GPLv2+

name=liblockfile
version=1.14
release=1
source=(ftp://ftp.debian.org/debian/pool/main/libl/liblockfile/liblockfile\_$version.orig.tar.gz)

build() {
	cd $name

	 ./configure --prefix=/usr \
	            --build=$BUILD \
	            --host=$HOST \
	            --enable-shared

	make -j$JOBS
	make DESTDIR=$PKG install
}
