# Description: A library which supports many formats, including: mod, s3m, it, and xm.
# URL: http://mikmod.shlomifish.org/

name=libmikmod
version=3.3.6
release=1
source=(http://downloads.sourceforge.net/project/mikmod/$name/$version/$name-$version.tar.gz)
depends=(alsa-lib)

build(){
   cd $name-$version

   sed -i docs/Makefile.in \
        -e 's|^INFO_DEPS = .*|INFO_DEPS =|g'
 
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-alsa \
               --mandir=/usr/share \
               --disable-esd \
               --disable-oss \
               --disable-dependency-tracking

   make -j $JOBS
   make DESTDIR=$PKG install

   chmod a+x $PKG/usr/lib/*.la

   # Fix libtool files
   fix_la_files $PKG
}
