# Description: Vorbis codec library
# URL: http://www.xiph.org/ogg/vorbis/

name=libvorbis
version=1.3.3
release=1
source=(http://downloads.xiph.org/releases/vorbis/$name-$version.tar.xz)
depends=(libogg)

build() {
  cd $name-$version

  ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr

  make -j $JOBS
  make DESTDIR=$PKG install

  rm -rf $PKG/usr/share/doc

  # Fix libtool files
  fix_la_files $PKG
}
