# Description: A sample multi-channel audio mixer library.
# URL: http://www.libsdl.org/projects/SDL_mixer/
# Maintainer: Danny Rawlins, monster dot romster at gmail dot com
# Packager: Simone Rota, sip at crux dot nu
# Depends on: libvorbis smpeg libmikmod flac

name=sdl_mixer
version=1.2.12
release=1
source=(http://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-$version.tar.gz)
depends=(libvorbis smpeg libmikmod flac)

build() {
   cd SDL_mixer-$version

   sed -i -e 's|/usr/local/lib/timidity|/usr/share/timidity|g' timidity/config.h

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

#               --enable-music-mod \
#               --with-smpeg-prefix=$SYSROOT

#   MODPLUG_CFLAGS="-I $SYSROOT/usr/include" \
#   SDL_CFLAGS="-I $SYSROOT/usr/include" \
#   CFLAGS="-I $SYSROOT/usr/include" \
#   MODPLUG_LIBS=$SYSROOT/usr/lib \
#   SDL_LIBS=$SYSROOT/usr/lib \
   make
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
