# Description: A multi-platform toolkit for creating graphical user interfaces
# URL: http://www.gtk.org/

name=gtk3
version=3.4.4
release=1
source=(http://ftp.gnome.org/pub/gnome/sources/gtk+/3.4/gtk+-$version.tar.xz)
depends=(atk gdk-pixbuf hicolor-icon-theme libtiff pango libSM libXcursor libXrandr libXi)

build () {
   cd gtk+-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-xkb \
               --disable-xinerama \
               --disable-glibtest \
               --disable-cups \
               --with-x

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{locale,gtk-doc} 

   # Fix libtool files
   fix_la_files $PKG
}
