# Description: A multi-platform toolkit for creating graphical user interfaces
# URL: http://www.gtk.org/

name=gtk3
version=3.10.2
release=1
source=(http://ftp.gnome.org/pub/gnome/sources/gtk+/${version%.*}/gtk+-$version.tar.xz)
depends=(atk at-spi2-atk gdk-pixbuf hicolor-icon-theme libtiff pango libSM libXcursor libXrandr libXi)

build () {
   cd gtk+-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-xkb \
               --disable-xinerama \
               --disable-glibtest \
               --disable-cups \
               --with-x \
               --enable-gtk2-dependency

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{locale,gtk-doc,gtk-3.0,glib-2.0} 

   # Fix libtool files
   fix_la_files $PKG
}
