# Description: Python interpreter
# URL: http://www.python.org
# Depends on: db gdbm ncurses openssl readline bzip2 zlib

name=python
version=3.4.3
release=1
source=(https://www.python.org/ftp/$name/$version/Python-$version.tar.xz \
        config.site)
depends=(db gdbm openssl readline bzip2 zlib)

build () {
  cd Python-$version

  CC="$HOST-gcc" CXX="$HOST-g++" \
  AR="$HOST-ar" RANLIB="$HOST-ranlib" \
  CONFIG_SITE=$SRC/config.site ./configure --build=$BUILD \
              --host=$HOST \
              --prefix=/usr \
              --enable-shared \
              --with-threads \
              --without-gcc \
              --disable-ipv6 \
              --with-cxx-main=$HOST-gcc

  make -j $JOBS

  make DESTDIR=$PKG install

  rm -rf $PKG/usr/lib/$name/{bsddb,ctypes,email,sqlite3}/test
  rm -rf $PKG/usr/lib/$name/{distutils,json,lib2to3}/tests
  rm -f $PKG/usr/lib/$name/{distutils,site-packages,test}/README
  rm -f $PKG/usr/lib/$name/idlelib/{ChangeLog,{NEWS,README,TODO}.txt}
  rm -f $PKG/usr/lib/$name/ctypes/macholib/README.ctypes
}
