# Description: Python interpreter
# URL: http://www.python.org
# License: PSFv2

name=python
version=3.5.1
release=1
source=(https://www.python.org/ftp/$name/$version/Python-$version.tar.xz \
        0001-setup.py-do-not-add-invalid-header-locations.patch \
        0002-Change-the-install-location-of-_sysconfigdata.py.patch \
        0003-Make-the-build-of-pyc-files-conditional.patch \
        0004-Disable-buggy_getaddrinfo-configure-test-when-cross-.patch \
        0005-Add-infrastructure-to-disable-the-build-of-certain-e.patch \
        0006-distutils-sysconfig-use-sysconfigdata.patch \
        0007-Adjust-library-header-paths-for-cross-compilation.patch \
        0008-Don-t-look-in-usr-lib-termcap-for-libraries.patch \
        0009-Don-t-add-multiarch-paths.patch \
        0010-Abort-on-failed-module-build.patch \
        0011-Serial-ioctl-workaround.patch \
        0012-Do-not-adjust-the-shebang-of-Python-scripts-for-cros.patch \
        0013-Misc-python-config.sh.in-ensure-sed-invocations-only.patch \
        0014-Do-not-harcode-invalid-path-to-ncursesw-headers.patch \
        0015-Override-system-locale-and-set-to-default-when-addin.patch \
        0016-Add-importlib-fix-for-PEP-3147-issue.patch \
        0017-Add-an-option-to-disable-installation-of-test-module.patch \
        0018-Add-an-option-to-disable-pydoc.patch \
        0019-Add-an-option-to-disable-lib2to3.patch \
        0020-Add-option-to-disable-the-sqlite3-module.patch \
        0021-Add-an-option-to-disable-the-tk-module.patch \
        0022-Add-an-option-to-disable-the-curses-module.patch \
        0023-Add-an-option-to-disable-expat.patch \
        0024-Add-an-option-to-disable-CJK-codecs.patch \
        0025-Add-an-option-to-disable-NIS.patch \
        0026-Add-an-option-to-disable-unicodedata.patch \
        0027-Add-an-option-to-disable-IDLE.patch \
        0028-Add-an-option-to-disable-decimal.patch \
        0029-Add-an-option-to-disable-the-ossaudiodev-module.patch \
        0030-Support-PGEN_FOR_BUILD-and-FREEZE_IMPORTLIB_FOR_BUIL.patch \
        0031-bypass-build-tools.patch)

depends=(db gdbm openssl readline bzip2 zlib)

build () {
    cd Python-$version

    for file in $SRC/*.patch
    do
        patch -p1 -i $file
    done

    autoreconf -i

    CC="$HOST-gcc" \
    CXX="$HOST-g++" \
    AR="$HOST-ar" \
    RANLIB="$HOST-ranlib" \
    ac_cv_have_long_long_format=yes \
    ac_cv_file__dev_ptmx=yes \
    ac_cv_file__dev_ptc=yes \
    ac_cv_working_tzset=yes \
    ./configure --build=$BUILD            \
                --host=$HOST              \
                --prefix=/usr             \
                --enable-shared           \
                --with-threads            \
                --without-gcc             \
                --disable-ipv6            \
                --with-cxx-main=$HOST-gcc \
                --without-ensurepip       \
                --with-system-ffi         \
                --disable-pydoc           \
                --disable-test-modules    \
                --disable-lib2to3         \
                --disable-tk              \
                --disable-nis             \
                --disable-idle3           \
                --disable-pyc-build

    make -j $JOBS

    make DESTDIR=$PKG install
}
