# Description: The Mozilla Firefox browser
# URL: http://www.mozilla.org

name=firefox
version=25.0
release=1
source=(http://download.cdn.mozilla.net/pub/mozilla.org/$name/releases/$version/source/$name-$version.source.tar.bz2
        firefox.mozconfig)
depends=(gtk2 cairo dbus dbus-glib libpng libffi zlib libX11 libXt MesaLib alsa-lib
         gst-plugins-base-0.10 gstreamer-0.10)

build () {
   cd mozilla-release

   cp $SRC/firefox.mozconfig .mozconfig
   echo "ac_add_options --prefix=/usr" >> .mozconfig
   echo "ac_add_options --host=$BUILD" >> .mozconfig
   echo "ac_add_options --target=$HOST" >> .mozconfig
   echo "mk_add_options MOZ_MAKE_FLAGS=-j$JOBS" >> .mozconfig

   make -f client.mk build
   make -f client.mk DESTDIR=$PKG install

   rm -r $PKG/usr/include
   rm -r $PKG/usr/lib/firefox-devel-*
   rm -r $PKG/usr/share
}

check () {
   check_tool zip
   check_tool yasm
}
