# Description: SQL database server
# URL:         http://www.mysql.com
# Depends on:  tcp_wrappers ncurses zlib openssl cmake libaio

name=mysql
version=5.5.29
release=1
source=(http://mirror.switch.ch/mirror/mysql/Downloads/MySQL-5.5/$name-$version.tar.gz \
        mysql_va_list.patch mysqld.service mysqld_install.service install_mysql)
depends=(openssl zlib libaio ncurses tcp_wrappers)

build () {
   cd $name-$version

   patch -p1 < $SRC/mysql_va_list.patch

   cmake .
   make -j $JOBS
   cp extra/comp_err $SRC
   cp scripts/comp_sql $SRC
   cp sql/gen_lex_hash $SRC
   rm CMakeCache.txt
   make clean

   export PATH=$SRC:$PATH

   cmake -DCMAKE_INSTALL_PREFIX=/usr \
         -DCMAKE_SYSTEM_NAME=Linux \
         -DCMAKE_C_COMPILER=$HOST-gcc \
         -DCMAKE_CXX_COMPILER=$HOST-g++ \
         -DCMAKE_LINKER=$NATIVE_SYSROOT/bin/$HOST-ld \
         -DCMAKE_AR=$NATIVE_SYSROOT/bin/$HOST-ar \
         -DCMAKE_NM=$NATIVE_SYSROOT/bin/$HOST-nm \
         -DCMAKE_OBJDUMP=$NATIVE_SYSROOT/bin/$HOST-objdump \
         -DCMAKE_RANLIB=$NATIVE_SYSROOT/bin/$HOST-ranlib \
         -DCMAKE_STRIP=$NATIVE_SYSROOT/bin/$HOST-strip \
         -DSTACK_DIRECTION=1 \
         -DSYSCONFDIR=/etc \
         -DINSTALL_LIBDIR=lib \
         -DINSTALL_PLUGINDIR=lib/mysql/plugin \
         -DWITH_EMBEDDED_SERVER=TRUE \
         -DWITH_LIBWRAP=1 \
         -DWITH_SSL=system \
         -DCURSES_LIBRARY=$SYSROOT/usr/lib/libncurses.a \
         -DCURSES_INCLUDE_PATH=$SYSROOT/usr/include \
         -DWITH_ZLIB=system \
         -DZLIB_LIBRARY=$SYSROOT/usr/lib/libz.a \
         -DZLIB_INCLUDE_DIR=$SYSROOT/usr/include \
         -DCMAKE_FIND_ROOT_PATH=$SYSROOT \
         -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
         -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
         -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
         -DINSTALL_LAYOUT=RPM

   cp ../comp_err extra/
   cp ../comp_sql scripts/
   cp ../gen_lex_hash sql/

#        -DWITH_SSL=system
#        -DBUILD_CONFIG=mysql_release \
#        -DMYSQL_DATADIR=$DEST/data

   make -j$JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{mysql-test,info}
   rm $PKG/usr/share/mysql/charsets/README

   install -d $PKG/var/lib/mysql
   install -Dm 600 $SRC/mysqld.service $PKG/etc/systemd/system/mysqld.service
   install -Dm 600 $SRC/mysqld_install.service $PKG/etc/systemd/system/mysqld_install.service
   install -Dm 500 $SRC/install_mysql $PKG/usr/bin/install_mysql
#   find $PKG/usr/share/mysql/* -type d ! -name english ! -name charsets | xargs rm -r {} \;

#   install -d  $PKG/var/{lib,log}
#   touch mysqld.log
#   install -m 600 -o mysql -g mysql mysqld.log $PKG/var/log
#   install -d -m 700 -o mysql -g mysql $PKG/var/lib/mysql
#   install -D -m 755 $SRC/mysqld $PKG/etc/rc.d/mysqld
#   install -m 600 $SRC/my.cnf $PKG/etc
}

check() {
   check_tool cmake
}
