# Description: SQL database server
# URL:         http://www.mysql.com

name=mysql
version=5.6.12
release=1
source=(http://mirror.switch.ch/mirror/mysql/Downloads/MySQL-5.6/$name-$version.tar.gz \
        mysql_va_list.patch mysqld.service
        mysql-bug.67018.patch mysql-perfschema-zlib.patch)
depends=(openssl libaio ncurses tcp_wrappers perl)

build () {
   cd $name-$version

   patch -p1 < $SRC/mysql_va_list.patch

   cmake -DWITH_ZLIB=bundled .

   make comp_err comp_sql gen_lex_hash gen_pfs_lex_token -j$JOBS

   cp extra/comp_err $SRC
   cp scripts/comp_sql $SRC
   cp sql/gen_lex_hash $SRC
   cp storage/perfschema/gen_pfs_lex_token $SRC
   rm CMakeCache.txt
   make clean

   export PATH=$SRC:$PATH

   cmake -DCMAKE_INSTALL_PREFIX=/usr \
         -DCMAKE_SYSTEM_NAME=Linux \
         -DCMAKE_C_COMPILER=$HOST-gcc \
         -DCMAKE_CXX_COMPILER=$HOST-g++ \
         -DCMAKE_LINKER=$NATIVE_SYSROOT/bin/$HOST-ld \
         -DCMAKE_AR=$NATIVE_SYSROOT/bin/$HOST-ar \
         -DCMAKE_NM=$NATIVE_SYSROOT/bin/$HOST-nm \
         -DCMAKE_OBJDUMP=$NATIVE_SYSROOT/bin/$HOST-objdump \
         -DCMAKE_RANLIB=$NATIVE_SYSROOT/bin/$HOST-ranlib \
         -DCMAKE_STRIP=$NATIVE_SYSROOT/bin/$HOST-strip \
         -DCMAKE_CROSSCOMPILING=TRUE \
         -DSTACK_DIRECTION=1 \
         -DSYSCONFDIR=/etc \
         -DINSTALL_LIBDIR=lib \
         -DINSTALL_PLUGINDIR=lib/mysql/plugin \
         -DWITH_EMBEDDED_SERVER=TRUE \
         -DWITH_LIBWRAP=1 \
         -DWITH_SSL=system \
         -DCURSES_LIBRARY=$SYSROOT/usr/lib/libncurses.a \
         -DCURSES_INCLUDE_PATH=$SYSROOT/usr/include \
         -DWITH_ZLIB=bundled \
         -DCMAKE_FIND_ROOT_PATH=$SYSROOT \
         -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
         -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
         -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
         -DINSTALL_LAYOUT=RPM \
         -DCMAKE_C_FLAGS="-Wno-psabi" \
         -DCMAKE_CXX_FLAGS="-Wno-psabi"

   cp ../comp_err extra/
   cp ../comp_sql scripts/
   cp ../gen_lex_hash sql/
   cp ../gen_pfs_lex_token storage/perfschema/

   make -j$JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{mysql-test,info}
   rm $PKG/usr/share/mysql/charsets/README

   install -d $PKG/var/lib/mysql
   install -Dm 600 $SRC/mysqld.service $PKG/etc/systemd/system/mysqld.service
}

check() {
   check_tool cmake
}
