# Description: A free and open source (GPL) software media player and entertainment hub for digital media
# URL: http://xbmc.org/

name=xbmc
version=xbmc-rbp-efef226
release=1
source=(http://www.buildgear.org/mirror/raspberrypi/$name-$version.tar.gz
        xbmc-omxplayer-stringutils-fix.patch)
depends=(boost
         bzip2
         curl
         enca
         faad2
         fribidi
         gettext
         glew
         jasper
         libass
         libcdio
         libjpeg
         libmad
         libmicrohttpd
         libmms
         libmodplug
         libmpeg2
         libpcre
         libpng
         libsamplerate
         libtiff
         libusb
         lzo
         mysql
         python
         samba
         systemd
         sqlite
         tinyxml
         util-linux
         yasm
         yajl
         wavpack
         vc)

build() {
   cd $name-$version

   patch -p1 < $SRC/xbmc-omxplayer-stringutils-fix.patch

   ./bootstrap

   PYTHON_VERSION="2.7" \
   PYTHON_SITE_PKG="$SYSROOT/usr/lib/python2.7/site-packages" \
   PYTHON_CPPFLAGS="-I$SYSROOT/usr/include/python" \
   PYTHON_LDFLAGS="-L$SYSROOT/usr/lib -lpython2.7 -lpthread -ldl -lutil -lm" \
   PYTHON_NOVERSIONCHECK="no-check" \
   LDFLAGS="-L$SYSROOT/usr/lib" \
   INCLUDES="-I$SYSROOT/usr/include" \
   MYSQL_CONFIG=yes \
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-arch=arm \
               --disable-debug \
               --disable-rsxs \
               --with-platform=raspberry-pi \
               --disable-webserver \
               --enable-gles \
               --disable-sdl \
               --disable-x11 \
               --disable-xrandr \
               --disable-openmax \
               --disable-optical-drive \
               --disable-dvdcss \
               --disable-joystick \
               --disable-crystalhd \
               --disable-vtbdecoder \
               --disable-vaapi \
               --disable-vdpau \
               --disable-pulse \
               --disable-projectm \
               --disable-optimizations

   make DVDREAD_CFLAGS="-I$SYSROOT/usr/include" \
        DVDREAD_LIBS="-L$SYSROOT/usr/lib -ldvdread" \
        PNG_CFLAGS="-I$SYSROOT/usr/include" \
        PNG_LIBS="-L$SYSROOT/usr/lib"
   make DESTDIR=$PKG install
}

check() {
   check_tool autopoint
   check_tool zip
   # TODO: Add checks for liblzo2-dev liblzo2-2 libsdl-image1.2-dev
}
