# Description: A free and open source (GPL) software media player and entertainment hub for digital media
# URL: http://xbmc.org/

name=xbmc
version=11.0
release=1
source=(http://mirrors.xbmc.org/releases/source/$name-$version.tar.gz
        xbmc-arch-fix.patch xbmc-mysql-fix.patch)
depends=(boost
         bzip2
         curl
         enca
         faad2
         fribidi
         gettext
         glew
         jasper
         libass
         libcdio
         libjpeg
         libmad
         libmicrohttpd
         libmms
         libmodplug
         libmpeg2
         libpcre
         libsamplerate
         libtiff
         libusb
         lzo
         mysql
         python
         samba
         SDL_mixer
         SDL_image
         systemd
         sqlite
         util-linux
         yasm
         yajl
         wavpack)

build() {
   cd $name-$version

   patch -p1 < $SRC/xbmc-arch-fix.patch
   patch -p1 < $SRC/xbmc-mysql-fix.patch

   ./bootstrap

   ac_python_version="2.7" \
   PYTHON_EXTRA_LIBS="-L$SYSROOT/usr/lib" \
   PYTHON_EXTRA_LDFLAGS="-L$SYSROOT/usr/lib -lpython2.7" \
   PYTHON_SITE_PKG="-L$SYSROOT/usr/lib/python/dist-packages" \
   PYTHON_CPPFLAGS="-I$SYSROOT/usr/include/python" \
   PYTHON_LDFLAGS="-L$SYSROOT/usr/lib" \
   LDFLAGS="-L$SYSROOT/usr/lib" \
   INCLUDES="-I$SYSROOT/usr/include" \
   MYSQL_CONFIG=yes \
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-arch=arm \
               --with-cpu=arm1176jzf-s \
               --disable-debug

   make DVDREAD_CFLAGS="-I$SYSROOT/usr/include" \
        DVDREAD_LIBS="-L$SYSROOT/usr/lib -ldvdread"
   make DESTDIR=$PKG install
}

check() {
   check_tool autopoint
   check_tool zip
}
