# Description: Free Lossless Audio Codec.
# URL: http://flac.sourceforge.net/

name=flac
version=1.3.1
release=1
source=(http://downloads.xiph.org/releases/$name/$name-$version.tar.xz)
depends=(libogg)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-ogg=$SYSROOT/usr/lib \
               --disable-xmms-plugin

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
