# Description: SDL_image is an image file loading library.
# URL: http://www.libsdl.org/projects/SDL_image

name=sdl_image
version=1.2.12
release=1
source=(http://www.libsdl.org/projects/SDL_image/release/SDL_image-$version.tar.gz)
depends=(libtiff libpng libsdl)

build() {
   cd SDL_image-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
