# Description: tmux is a terminal multiplexer
# URL: http://tmux.sourceforge.net/

name=tmux
version=1.9a
release=1
source=(http://downloads.sourceforge.net/project/$name/$name/$name-${version%[a-z]}/$name-$version.tar.gz)
depends=(ncurses libevent)

build() {
   cd $name-$version

   ./configure --prefix=/usr  \
               --host=$HOST   \
               --build=$BUILD \
               LIBS=-ltinfo

   make -j$JOBS
   make DESTDIR=$PKG install
}
