# Description: Fast, lightweight, standards-compliant window manager
# URL: http://openbox.org

name=openbox
version=3.5.0
release=1
source=(http://openbox.org/dist/openbox/openbox-$version.tar.gz
        openbox.service xinitrc)
depends=(libXrandr libSM glib libxml2 pango which)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               --libexecdir=/usr/lib/openbox

   make -j $JOBS
   make DESTDIR=$PKG install

   mv $PKG/usr/share/doc/$name/*.xsd $PKG/usr/etc/xdg/$name
   rm -rf $PKG/usr/share/doc

   install -D -m744 $SRC/xinitrc $PKG/root/.xinitrc
   install -D -m644 $SRC/openbox.service $PKG/etc/systemd/system/openbox.service

   # Fix libtool files
   fix_la_files $PKG
}
