# Description: Unicode Bidirectional (BiDi) Algorithm.
# URL: http://fribidi.org/

name=fribidi
version=0.19.7
release=1
source=(http://fribidi.org/download/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
