# Description: HarfBuzz is an OpenType text shaping engine.
# URL: http://www.freedesktop.org/wiki/Software/HarfBuzz

name=harfbuzz
version=0.9.12
release=1
source=(http://www.freedesktop.org/software/$name/release/$name-$version.tar.bz2)
depends=(freetype glib)

build () {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

}
