# Description: SDL, Simple DirectMedia Layer 
# URL: http://www.libsdl.org

name=libsdl
version=1.2.15
release=1
source=(http://www.libsdl.org/release/SDL-$version.tar.gz)
depends=(alsa-lib MesaLib)

build () {
   cd SDL-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
                --enable-alsa \
                --mandir=/usr/man

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
