# Description: An RFC2131-compliant DHCP client daemon
# URL: http://roy.marples.name/dhcpcd

name=dhcpcd
version=6.11.1
release=1
source=(http://roy.marples.name/downloads/$name/$name-$version.tar.xz
        dhcpcd@.service)

build () {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --libexecdir=/usr/lib/dhcpcd \
               --dbdir=/var/lib/dhcpcd \
               --sysconfdir=/etc/dhcpcd \
               --os=linux \
               --with-hooks=none

   make -j $JOBS
   make DESTDIR=$PKG install

   install -Dm644 $SRC/dhcpcd@.service $PKG/etc/systemd/system/dhcpcd@.service
   chmod -R u+w $PKG
}
