# Description: a high quality MPEG Audio Layer III (MP3) encoder
# URL: http://lame.sourceforge.net/
# License: LGPLv2

name=lame
version=3.99.5
release=1
source=(http://downloads.sourceforge.net/project/lame/lame/3.99/lame-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --prefix=/usr \
               --host=$HOST \
               --build=$BUILD \
               --disable-frontend

   make -j$JOBS
   make DESTDIR=$PKG install

   fix_la_files $PKG
}
