# Description: Utility for controlling network drivers and hardware
# URL: https://www.kernel.org/pub/software/network/ethtool/
# License: GPLv2

name=ethtool
version=3.15
release=1
source=(https://www.kernel.org/pub/software/network/ethtool/ethtool-$version.tar.xz)
depends=()

build() {

   cd $name-$version

   ./configure \
      --prefix=/usr \
      --build=$BUILD \
      --host=$HOST

   make -j$JOBS
   make DESTDIR=$PKG install

}

