# Description: A tool for transfering files with URL syntax
# URL: http://curl.haxx.se
# License: MIT GPL BSD LGPL

name=curl
version=7.52.1
release=1
source=(http://curl.haxx.se/download/$name-$version.tar.bz2)
depends=(openssl zlib)

build() {
    cd $name-$version

    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --mandir=/usr/share \
                --disable-nls

    make -j $JOBS
    make DESTDIR=$PKG install

    # Cleanup
    rm -r $PKG/usr/share/man3

    # Fix libtool files
    fix_la_files $PKG
}
