# Description: A library to provide an API to MPEG-4 files.
# URL: http://code.google.com/p/mp4v2/

name=libmp4v2
version=1.9.1
release=1
source=(http://mp4v2.googlecode.com/files/mp4v2-$version.tar.bz2)

build() {
   cd mp4v2-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --mandir=/usr/share/man \
               --disable-static \
               --disable-gch

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
